[project]
name = "durden"
version = "0.1.0"
description = ""
authors = [
    {name = "Mallem Sofiane",email = "melsopv@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "fastapi (>=0.139.0,<0.140.0)",
    "uvicorn (>=0.50.2,<0.51.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "python-multipart (>=0.0.32,<0.0.33)",
    "pillow (>=12.3.0,<13.0.0)",
    "ruff (>=0.15.20,<0.16.0)",
    "ultralytics (>=8.4.90,<9.0.0)",
    "pydantic-settings (>=2.14.2,<3.0.0)",
    "torch",
    "torchvision"
]

[tool.poetry]
packages = [{include = "durden", from = "src"}]

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.dependencies]
torch = [
    { markers = "sys_platform == 'darwin'", source = "PyPI" },
    { markers = "sys_platform == 'linux'", source = "pytorch-cpu" },
]
torchvision = [
    { markers = "sys_platform == 'darwin'", source = "PyPI" },
    { markers = "sys_platform == 'linux'", source = "pytorch-cpu" },
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "deptry (>=0.25.1,<0.26.0)"
]