name: CI

on:
  push:
  pull_request:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run lint
        run: poetry run ruff check .

      - name: Run tests
        env:
          name: "Durden Object Detection API"
          models: '["yolov8n.pt","yolov8s.pt"]'
          env: "test"
          version: "0.1.0"
          static_dir: "src/durden/static"
        run: poetry run pytest

  docker-build:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase image name
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
  
  deploy:
      needs: docker-build
      runs-on: ubuntu-latest

      permissions:
        id-token: write
        contents: read

      steps:
        - name: Authenticate Google Cloud
          uses: google-github-actions/auth@v2
          with:
            workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
            service_account: github-actions-deployer@project-df4f98a7-7326-426c-bc0.iam.gserviceaccount.com

        - name: Deploy Cloud Run
          uses: google-github-actions/deploy-cloudrun@v2
          with:
            service: durden
            region: europe-west1
            image: ${{ needs.docker-build.outputs.image }}